// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

library Errors {
    string constant ERROR_CANNOT_EXECUTE_REJECTED_PROPOSAL = "ERROR_CANNOT_EXECUTE_REJECTED_PROPOSAL";
    string constant ERROR_INSUFFICIENT_BALANCE = "ERROR_INSUFFICIENT_BALANCE";
    string constant ERROR_NOT_FOUND = "ERROR_NOT_FOUND";
    string constant ERROR_COLLISION = "ERROR_COLLISION";
    string constant ERROR_EXPIRED = "ERROR_EXPIRED";
    string constant ERROR_ALREADY_EXECUTED = "ERROR_ALREADY_EXECUTED";
    string constant ERROR_QUORUM_IS_NOT_REACHED = "ERROR_QUORUM_IS_NOT_REACHED";
    string constant ERROR_TREASURY_INSUFFICIENT_BALANCE = "ERROR_TREASURY_INSUFFICIENT_BALANCE";
    string constant ERROR_ZERO_ADDRESS = "ERROR_ZERO_ADDRESS";
    string constant ERROR_QUEUE_IS_FULL = "ERROR_QUEUE_IS_FULL";
    string constant UINT32_NUMBER_TOO_BIG = "UINT32_NUMBER_TOO_BIG";
    string constant ERROR_VETOED = "ERROR_VETOED";
    string constant NO_VETO_RIGHT = "NO_VETO_RIGHT";
}